### PR TITLE
remote exception from wordsection

### PR DESCRIPTION
**Pull request by crjc**
I wasn't able to use this lib due to this exception being thrown. I've noticed a similar exception in the code base was commented out, so my quick 'fix' was to do the same here.

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
Well I would prefer you add a check what type it is missing so maybe we can add a support for it? Just do the debug on it, stop, and see what type it is and add if else. This would allow us to track/and fix it

**Comment by crjc** [comment]
I've added the two types that I found were missing based on my document files. The exception might trip up on other people's documents, but I added it back anyhow.

**Comment by PrzemyslawKlys** [comment]
Maybe it would be better to comment it out and just add some sort of output, to log a ticket? on the other hand if it's not defined  like you just did people will keep on creating ticket for types - that are not defined. I am not sure what's better.

**Comment by crjc** [comment]
Not sure if this is OK, but I've added a flag to WordDocument which allows for this exception to be disabled. I would have found this useful for my use case earlier.

The exception thrown by default now has a more informative message, summarising what type hasn't been handled and encouraging the user to create an issue here.

**Comment by PrzemyslawKlys** [comment]
I've been thinking on it and while I believe your solution would make most sense, I am pro removing all elseif/else and just leave Header/Footer references. 

If you won't interact with GutterOnRight or Bidi it will not be removed hence there's no need to throw on it at all. Anything else such as Guitter, PageMargins and so on are already added. 

If someone (you?) wants support for GutterOnRight, GutterOnTop or similar
- https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.gutteronright?view=openxml-2.8.1

We should simply create new issue and open "support" for given functionality. 

It should not throw on this because it's confusing and just not useful. Can you please remove it? I think it will make most sense? What do you think? 

And if we really want to support your document type fully we should just understand what those settings are and define them, and fix them in some near future.

**Comment by PrzemyslawKlys** [comment]
I've opened the issues:
- #101 
- #102 

To track those unsupported elements

**Comment by crjc** [comment]
Thanks! I think that makes sense, so do you think I should remove the two if/else I added, and replace the exception with a simple `Debug.WriteLine` message?

**Comment by PrzemyslawKlys** [comment]
Ye, adding debug.writeline makes sense, so that this can be "seen" but at some point when the project will mature enough we will completely remove it.

**Comment by crjc** [comment]
Here we are, by the way - if this PR looks okay now, are you planning on doing a new release sometime soon?

**Comment by PrzemyslawKlys** [comment]
I will release today after I get back from shops.

**Comment by PrzemyslawKlys** [comment]
Scratch that - here you go!

**Pull request merged**
