### PR TITLE
[WordTextBox] Add additional features

### PR DESCRIPTION
**Pull request by TopperDEL**
This PR adds the following features:
- Use Paragraph instead of StdBlock (so that text within a TextBox is no "variable" anymore)
- Allow changing the insets of the TextBox so that there is no gap between the text of the TextBox and its border
- Allow the TextBox to be set to "AutoFitText" or not
- Allow the text to be multiline by respecting the page breaks
- Added Wrapping functionality including inline
- Added ability to convert inline to other wrapping types and vice versa (keep in mind that some properties are lost then or go to their defaults)
- Fixes wrong paragraph being returned when AddImage is used

Breaking change:
- Changes `WrapTextImage.InFrontText` to `WrapTextImage.InFrontOfText` to match Word naming

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
I've reworked your code a bit and removed boolean and instead created proper Wrapping functionality that is identical to the one in image. Anchor implements 90% of wrapping but we're missing Inline for both TextBox and Images. 

I've moved all the logic around wrapping to separate class, as I guess we will need to somehow expose other parameters of wrapping that are visible in WrapThrough and WrapTight and potentially in WrapTopBottom. 

I am not sure how to do this, as I'm too noobish on classes, but maybe I'll figure it out. 

This PR needs tests written before it can be commited + Add method in sections.

**Comment by PrzemyslawKlys** [comment]
- Added some testing, but should be more tests on the new features that were added
- Added option to add textbox per section

**Comment by TopperDEL** [comment]
Awesome @PrzemyslawKlys! I've been in another project for over a week, but I'll come back to this one soon. Will try what you made and see where I may help. Thanks!

**Comment by PrzemyslawKlys** [comment]
- Added inline with text so that it works properly now
- Added ability to convert from inline to anchor and back (as inline doesn't have some properties it removes them from anchor, and vice versa - as inline doesn't have some properties during conversion to anchor defaults are applied).
- Fixed AddImage returning wrong paragraph which would cause issues in some cases
- Improved testing

**Comment by TopperDEL** [comment]
Do you plan to create a new release with these changes?

**Comment by PrzemyslawKlys** [comment]
Sure, probably before Monday.  I want to play with some other stuff.

**Comment by PrzemyslawKlys** [comment]
Something went terribly wrong with this PR, as even tho merge went in, it didn't went in with your or my changes?

**Comment by PrzemyslawKlys** [comment]
Ok i see it went into different branch

**Comment by TopperDEL** [comment]
Sorry for the confusion! I forked your repo and create a branch for it, if I remember correctly.

**Comment by PrzemyslawKlys** [comment]
Not your fault. It was mine. I was just super scared i lost everything 😂

**Comment by TopperDEL** [comment]
I feel you! 😂

**Pull request merged**
