### PR TITLE
Add Areachat

### PR DESCRIPTION
**Pull request by startewho**
It seems lack the area chat ,so I add this type.
image

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
That is great! Could you please add few more tests mostly around the chart itself? Could you also add an example in the example documents?

**Comment by startewho** [comment]
> That is great! Could you please add few more tests mostly around the chart itself? Could you also add an example in the example documents?
add the example and some chart count test

**Comment by PrzemyslawKlys** [comment]
I've added some modifications. For your change of int to <t> is that because it's possible to use float/double or what's the use case?

**Comment by startewho** [comment]
> 

yes,when I used the double for the electricity energy used like kw/h .thanks for your modify

**Pull request merged**
