### PR TITLE
Added WordParagraphStyles.Custom

### PR DESCRIPTION
**Pull request by ChrisBellBO**
Added WordParagraphStyles.Custom

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
Would you be able to add some tests for this?

**Comment by ChrisBellBO** [comment]
Added a test and fixed the tests that my original change broke. I've also updated the reference to SixLabors.ImageSharp due to a vulnerability

**Comment by PrzemyslawKlys** [comment]
you should maintain the old way it was written in config, it prevents updating to 3.0.0, which is not compatible :)

**Comment by ChrisBellBO** [comment]
I'm not sure I understand, I upgraded to 2.1.9 which doesn't have the vulnerability?

**Comment by PrzemyslawKlys** [comment]
image

The brackets that are used, prevent users from getting ImageSharp 3.0+ and claiming OfficeIMO doesn't work. Same for OpenXML. You should just set 2.1.9 as minimum, and maximum 2.X.X excluding 3.0.0 which is what the brackets do

**Comment by ChrisBellBO** [comment]
Got it, thanks. Fixed that

**Pull request merged**
