### PR TITLE
AddRow functions return the created rows and table cell VerticalAlignment property

### PR DESCRIPTION
**Pull request by The-Faulty**
See title

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
Thank you. Would you care enough to add basic tests for this?

**Comment by The-Faulty** [comment]
> Thank you. Would you care enough to add basic tests for this?

Sure, what do you mean by that though?

**Comment by PrzemyslawKlys** [comment]
Tests - something that confirms the methods works as expected the way you designed them so if someone changes the code later on - it will fail if don't wrongly.

**Comment by The-Faulty** [comment]
Got it. I'm a little busy for the next few days but I'll get to it soon.

**Comment by PrzemyslawKlys** [comment]
There's a time for everything :-) I don't know what I am doing most of the time with this project so you're in good company.

**Pull request merged**
